Fifth version of my portfolio at Microverse
Yothu/my-portfolio pull request #4
Opened 2021-11-30 21:17 UTC by Yothu

This is the "Contact me" section of the mobile version of my portfolio.

The files are:

- index.html
- css/style.css
- linters for HTML/CSS
- background images
- social media images
- miscellaneous images
- README.md
- MIT.md
- .gitignore

2021-11-30 22:41 UTC, MrBrN197 requested changes
## Hi, @Yothu  & @eduardosancho 👋 

You've done a really nice job so far.
There are some issues that you still need to work on to go to the next project but you are almost there!
## To highlight 👏👏
- ✔Really good form section design  👍.
- ✔Good clean code 👍.
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-30 22:41 UTC, MrBrN197 commented on index.html
> +      <button type="submit" id="submit">Get in touch</button>
- [ ] Your design looks really good. well done 👍. I'd like to point out however that the button on the Figma template doesn't have a border around the button. please try to fix this so your button matches the Figma template perfectly 🙏. 
## Your Design
![image](https://user-images.githubusercontent.com/18730106/144139028-91aea0d5-310e-4912-94cb-3136091e075c.png)
## Figma Design 
![image](https://user-images.githubusercontent.com/18730106/144139061-a11d9d3f-ddd0-4c3e-9643-0efe9bf7b413.png)

2021-11-30 22:41 UTC, MrBrN197 commented on index.html
> +      <button type="submit" id="submit">Get in touch</button>
- [ ] Hi the rest of your form design matches the Figma really well 👏. Although I'd like to mention that you have missed including a background image that is Visible on the Figma template. Please implement this
## Your Design
![image](https://user-images.githubusercontent.com/18730106/144139452-79370860-5245-406e-9ef5-38b73367c7d6.png)
## Figma Design
![image](https://user-images.githubusercontent.com/18730106/144139486-d43a9d42-e86f-4dbd-9cef-90a273e9f0ac.png)

2021-12-01 00:03 UTC, andersonlebon requested changes

2021-12-01 00:03 UTC, andersonlebon commented on index.html
> +      <button type="submit" id="submit">Get in touch</button>
- [x] Job job :+1:  :clap:  on making the changes requested by the previous reviewer. However, I can still see the same implementation
![Screenshot from 2021-12-01 01-48-07](https://user-images.githubusercontent.com/65068771/144147007-0b0d8f8e-b216-472d-aa71-99854c9224ed.png)

Kindly you may remove that border around the button by using the property `border: none` in the `#submit` attribute in your CSS.

2021-12-01 00:03 UTC, andersonlebon commented on index.html
> +      </label>
- [ ] Buy following the requirements and the suggestion of the previous reviewer this form has a background image. check the image bellow :point_down:
![Screenshot from 2021-12-01 01-47-20](https://user-images.githubusercontent.com/65068771/144147284-37ea3ac5-3dbe-4420-808e-391f88494f1f.png)

- [ ]  Kindly let's go ahead and add that background image.

2021-12-01 00:22 UTC, andersonlebon requested changes
## Hi @Yothu  

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub actions :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [x] Kindly check comments above :up: :arrow_up:  the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-01 00:34 UTC, carlos-ssh approved these changes
# 🍾🍾 **STATUS APPROVED** 👏🏽👏🏽

Hi @Yothu , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



![Approved](https://user-images.githubusercontent.com/22258274/138466108-6b14c541-6a88-44c5-ba76-c64992ac1835.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-01 00:38 UTC, merged